-- WOODCERT AUCTION - HUMAN-READABLE DATABASE INDEX
-- Last verified: 2026-06-19
--
-- IMPORTANT:
-- 1. This file is documentation only.
-- 2. Do not execute this file to create or migrate a database.
-- 3. The executable schema source of truth is:
--    woodcert-auction/src/main/resources/db/migration/
-- 4. Hibernate validates mappings; Flyway owns schema changes.
--
-- CURRENT MIGRATIONS
-- V1__baseline_schema.sql
--   Complete baseline schema.
-- V2__seed_reference_data.sql
--   Roles, permissions, role mappings, and categories.
-- V3__seed_demo_users.sql
--   Separate admin and appraiser accounts using password-hash placeholders.
-- V4__add_dispute_conversation.sql
--   Dispute messages and message-level evidence.
--
-- MODULE: IDENTITY AND ACCESS
-- users
-- roles
-- permissions
-- user_roles
-- role_permissions
-- refresh_tokens
-- email_verification_tokens
-- password_reset_tokens
-- seller_profiles
-- user_capability_statuses
-- admin_audit_logs
--
-- UserStatus:
--   ACTIVE, BANNED, UNVERIFIED
--
-- UserCapability:
--   BUYER, SELLER, APPRAISER
--
-- CapabilityStatus:
--   ACTIVE, BANNED
--
-- MODULE: LOCATION AND ADDRESS
-- provinces
-- districts
-- wards
-- addresses
--
-- Location primary/foreign keys use VARCHAR codes.
-- The first user address becomes default. Deleting the default address promotes
-- the oldest remaining address.
--
-- MODULE: MEDIA
-- media_assets
--
-- MediaStatus:
--   PENDING, ACTIVE, ORPHANED, PENDING_DELETE, DELETE_FAILED, DELETED
--
-- MediaUsageType:
--   USER_AVATAR, PRODUCT_IMAGE, APPRAISAL_IMAGE,
--   SHIPMENT_PACKING_VIDEO, DISPUTE_EVIDENCE
--
-- SHIPMENT_PACKING_VIDEO is reserved but not implemented by fulfillment.
--
-- MODULE: CATALOG AND APPRAISAL
-- categories
-- products
-- product_images
-- appraisal_reports
-- appraisal_images
--
-- ProductStatus:
--   DRAFT, PENDING_APPRAISAL, UNDER_APPRAISAL, REJECTED, APPRAISED
--
-- ProductSaleStatus:
--   AVAILABLE, IN_AUCTION, PENDING_ORDER, SOLD, RETURNED
--
-- Each product has at most one appraisal report.
-- Appraisal reports are immutable after submission.
-- Certificate format: CERT-{year}-{reportId padded to 5 digits}.
-- The integrity hash is SHA-256, not a digital signature or blockchain proof.
--
-- MODULE: FINANCE
-- wallets
-- wallet_transactions
-- wallet_operations
-- vnpay_deposits
-- platform_revenue_transactions
--
-- Wallets store available_balance and frozen_balance.
-- wallet_operations provides deterministic idempotency.
-- wallet_transactions records successful balance mutations.
-- platform_revenue_transactions records appraisal fees, sale commissions, and
-- forfeited-deposit platform fees.
--
-- The current system does NOT implement an independent escrow ledger.
--
-- WalletTransactionType:
--   WALLET_TOP_UP
--   APPRAISAL_FEE
--   AUCTION_DEPOSIT_FREEZE
--   AUCTION_DEPOSIT_RELEASE
--   AUCTION_DEPOSIT_CAPTURE
--   ORDER_PAYMENT
--   ORDER_REFUND
--   SELLER_PAYOUT
--   SELLER_FORFEIT_COMPENSATION
--
-- MODULE: AUCTION
-- auction_sessions
-- auction_participants
-- bids
--
-- AuctionSessionStatus:
--   WAITING, ACTIVE, ENDED_SUCCESS, ENDED_FAILED, CANCELED
--
-- DepositStatus:
--   FROZEN, WITHDRAWN, REFUNDED, DEDUCTED, CONFISCATED
--
-- BidStatus:
--   VALID, INVALID_PRICE, REJECTED_TIME
--
-- MySQL owns WAITING and terminal state.
-- Redis owns live current price, highest bidder, and end time during ACTIVE.
-- Public defaults: WAITING and ACTIVE.
-- Explicit public status/detail: WAITING, ACTIVE, ENDED_SUCCESS, ENDED_FAILED.
-- CANCELED is not public.
--
-- MODULE: ORDER
-- orders
--
-- OrderSourceType:
--   AUCTION
--
-- OrderStatus:
--   PENDING_PAYMENT, PAID, FULFILLING, COMPLETED, CANCELED, DISPUTED
--
-- Orders store immutable product and shipping-address snapshots plus financial
-- outcome fields. Buyer payment deadline defaults to 72 hours.
--
-- MODULE: FULFILLMENT
-- order_fulfillments
--
-- FulfillmentStatus:
--   PENDING_SHIPMENT, SHIPPED, DELIVERED, AUTO_COMPLETED, CANCELED
--
-- DeliveryMethod:
--   THIRD_PARTY, SELF_DELIVERY
--
-- Shipped fulfillment auto-completes after 168 hours by default when the order
-- is not disputed.
--
-- MODULE: DISPUTE
-- dispute_cases
-- dispute_messages
-- dispute_evidence
--
-- DisputeStatus:
--   OPEN, UNDER_REVIEW, RESOLVED, REJECTED, CANCELED
--
-- DisputeResolutionOutcome:
--   SELLER_WINS, BUYER_WINS
--
-- Opening evidence has message_id NULL.
-- Message evidence references dispute_messages.
-- Partial refunds are not implemented.
--
-- REDIS RUNTIME KEYS (NOT MYSQL TABLES)
-- auction:session:{id}:state
-- auction:session:{id}:bidders
-- auth:failed_attempts:{normalizedEmail}
-- auth:locked:{normalizedEmail}
--
-- See woodcert-auction/docs/DATABASE.md for the maintained schema overview.
