package com.woodcert.auction.feature.auction.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Append-only bid audit log.
 * bidTraceId is generated by BidService before Lua execution to link
 * the Redis winner snapshot with the MySQL audit row without depending
 * on a DB auto-increment that is not yet available at broadcast time.
 *
 * IMPORTANT: This table must never be updated or deleted.
 * Duplicate bidTraceId inserts must be silently ignored (no-op).
 */
@Getter
@Setter
@Entity
@Table(name = "bids", indexes = {
        @Index(name = "idx_bids_auction_session_bid_time", columnList = "auction_session_id,bid_time"),
        @Index(name = "idx_bids_auction_session_bid_amount", columnList = "auction_session_id,bid_amount"),
        @Index(name = "idx_bids_bid_time", columnList = "bid_time"),
        @Index(name = "uq_bids_bid_trace_id", columnList = "bid_trace_id", unique = true)
})
public class Bid {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "bid_trace_id", nullable = false, unique = true, length = 36)
    private String bidTraceId;

    @Column(name = "auction_session_id", nullable = false)
    private Long auctionSessionId;

    @Column(name = "user_id", nullable = false, length = 36)
    private String userId;

    @Column(name = "bid_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal bidAmount;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private BidStatus status;

    @Column(name = "bid_time", nullable = false)
    private Instant bidTime;
}
