server:
  port: 8080

spring:
  config:
    import: optional:classpath:application-local.yml

  application:
    name: woodcert-auction

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          "[time_zone]": UTC

  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:0}

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

jwt:
  secret-key: ${JWT_SECRET_KEY:}
  access-token-expiration: 900
  refresh-token-expiration: 604800

identity:
  location-seed:
    enabled: true
    api-url: https://provinces.open-api.vn/api/v1/?depth=3
  refresh-token-cleanup:
    enabled: true
    cron: "0 0 */6 * * *"
