package com.woodcert.auction.feature.identity.entity;

public enum AdminAction {
    ACCOUNT_BANNED,
    ACCOUNT_UNBANNED,
    BUYER_BANNED,
    BUYER_UNBANNED,
    SELLER_BANNED,
    SELLER_UNBANNED,
    APPRAISER_CREATED,
    APPRAISER_BANNED,
    APPRAISER_UNBANNED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    DISPUTE_MARKED_UNDER_REVIEW,
    DISPUTE_RESOLVED,
    REVENUE_EXPORTED
}
